const groups=[
[1,'饮水与饮品','白开水 柠檬水 西瓜 黄瓜 冬瓜 哈密瓜 杨桃 番茄 生菜 西葫芦'],[1,'奶类与豆制品','低脂牛奶 无糖酸奶 低盐奶酪 无糖豆浆 北豆腐 黑芝麻 杏仁 羽衣甘蓝 芥蓝'],[1,'蔬菜','白菜 卷心菜 西蓝花 莴笋 莲藕 胡萝卜 白萝卜 茄子 南瓜 青椒'],
[2,'水果','柠檬 橙子 柚子 苹果 梨 桃子 樱桃 蓝莓 火龙果 木瓜'],[2,'蛋白质','低脂牛奶 豆腐 鹰嘴豆 莲子 豌豆 藜麦 鸡蛋（蛋白） 鸡胸肉 火鸡肉 鳕鱼'],[2,'谷物与其他','燕麦 荞麦 藜麦 小米 糙米 玉米 红薯 山药 全麦面包 魔芋'],
[3,'饮水与饮品','浓茶 咖啡 奶茶 啤酒 可乐 酸梅汤 速溶果汁 功能饮料 骨头汤 肉汤'],[3,'奶类与豆制品','虾皮 鱼干 芝麻酱 冰淇淋 奶昔 奶油蛋糕 加工芝士 钙强化饮料 钙片 高钙保健品'],[3,'蔬菜','菠菜 苋菜 韭菜 甜菜叶 欧芹 马齿苋 秋葵 竹笋 苦瓜 芋头'],
[4,'水果','葡萄 草莓 黑莓 覆盆子 猕猴桃 无花果 石榴 杨桃 干枣 西梅干'],[4,'蛋白质','虾 蟹 贝类 沙丁鱼 凤尾鱼 动物内脏 腊肉 香肠 炸鸡 蛋白粉'],[4,'谷物与其他','方便面 薯片 膨化食品 火腿肠 咸鸭蛋 泡菜 咸菜 蜜饯 酱油 味精']];
const limits=new Set('奶茶 可乐 速溶果汁 功能饮料 奶昔 冰淇淋 奶油蛋糕 加工芝士 虾皮 鱼干 腊肉 香肠 炸鸡 方便面 薯片 膨化食品 火腿肠 咸鸭蛋 泡菜 咸菜 蜜饯 酱油 味精 动物内脏'.split(' '));
const checks=new Set('杨桃 黑芝麻 杏仁 芝麻酱 菠菜 苋菜 甜菜叶 欧芹 马齿苋 秋葵 竹笋 苦瓜 芋头 蛋白粉 钙片 高钙保健品 钙强化饮料 浓茶 咖啡 啤酒 骨头汤 肉汤 酸梅汤 鸡胸肉 火鸡肉 鳕鱼 虾 蟹 贝类 沙丁鱼 凤尾鱼 鸡蛋（蛋白）'.split(' '));
const seen=new Set();const foods=[];groups.forEach(([img,cat,names],g)=>names.split(' ').forEach((name,i)=>{if(seen.has(name))return;seen.add(name);if('西瓜 哈密瓜'.split(' ').includes(name))cat='水果';else if('黄瓜 冬瓜 番茄 生菜 西葫芦 羽衣甘蓝 芥蓝'.split(' ').includes(name))cat='蔬菜';else cat=groups[g][1];foods.push({name,img,cat,row:(g%3)*2+Math.floor(i/5),col:i%5,mode:checks.has(name)?'check':limits.has(name)?'limit':'daily'});}));
const labels={daily:'日常选择',limit:'注意适量',check:'因人而异'};let category='全部分类',mode='all';const cats=['全部分类','饮水与饮品','蔬菜','水果','奶类与豆制品','蛋白质','谷物与其他'];
function note(f){if(f.name==='杨桃')return '有肾脏疾病的人应避免食用杨桃。原图对杨桃的分类互相矛盾，不能据此推荐多吃；肾功能情况不明确时先咨询医生。';if(f.name==='白开水'||f.name==='柠檬水')return '白水是日常补水的优先选择；柠檬水不额外加糖，也不能代替结石治疗。饮水量需个体化，有限水医嘱时不要自行增加。';if(['钙片','高钙保健品','钙强化饮料'].includes(f.name))return '保持足够膳食钙不等于自行补充钙剂。是否需要补充、剂量与服用时机，应与医生讨论。';if(['菠菜','杏仁','黑芝麻','芝麻酱'].includes(f.name))return '草酸钙结石患者需留意草酸摄入。菠菜及坚果类尤其值得与营养师讨论，不将这类食物作为大量补钙来源。具体份量因个人情况而异。';if(f.mode==='limit')return '留意糖、盐及加工方式，减少高盐或高糖食品的频率和份量。查看营养标签，尽量选择新鲜、少加工、少加盐的替代品。';if(f.mode==='check')return '不直接判定为禁食或推荐大量食用。结合结石成分、整体饮食与肾功能，和医生或营养师确定份量；动物蛋白需考虑全天总量。';if(f.cat==='奶类与豆制品')return '可作为均衡膳食的一部分，留意配料与钠含量。不要因含钙结石自行限制正常膳食钙，具体份量按个人方案调整。';return '可作为多样化饮食的一部分，采用少盐、少糖的做法。日常选择不代表可以无限量食用；特殊限钾、限磷等要求需遵循医嘱。';}
function render(){document.querySelector('#categories').innerHTML=cats.map(c=>`<button class="${category===c?'active':''}" aria-pressed="${category===c}" data-cat="${c}">${c}<small>${c==='全部分类'?foods.length:foods.filter(f=>f.cat===c).length}</small></button>`).join('');const q=document.querySelector('#search').value.trim();const list=foods.filter(f=>(category==='全部分类'||category===f.cat)&&(mode==='all'||mode===f.mode)&&f.name.includes(q));document.querySelector('#count').textContent=`共 ${list.length} 种食物`;document.querySelector('#result-title').textContent=category==='全部分类'?'全部食物':category;document.querySelector('#empty').hidden=!!list.length;document.querySelector('#grid').innerHTML=list.map(f=>{const i=foods.indexOf(f);return `<button class="food" data-id="${i}" aria-label="查看${f.name}的饮食建议"><div class="food-image"><img src="assets/foods/${f.img}-${f.row}-${f.col}.png" alt="" loading="lazy"></div><div class="food-copy"><h3>${f.name}</h3><p>${f.cat}</p><span class="tag ${f.mode}">${labels[f.mode]}</span></div></button>`}).join('');}
document.querySelector('#categories').addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(b){category=b.dataset.cat;render();}});document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});render();}));document.querySelector('#search').addEventListener('input',render);const dialog=document.querySelector('#detail');document.querySelector('#grid').addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(!b)return;const f=foods[Number(b.dataset.id)];document.querySelector('#detail-body').innerHTML=`<h2>${f.name}</h2><span class="tag ${f.mode}">${labels[f.mode]}</span><p>${note(f)}</p><a href="#sources" id="source-go">查看参考来源 ↗</a>`;document.querySelector('#source-go').onclick=()=>dialog.close();dialog.showModal();});document.querySelector('#close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});render();



